### ISSUE TITLE
consumer crash

### ISSUE THREAD

**Issue by peterpribylina** [ricbra/rabbitmq-cli-consumer#16]
What happens if consumer crashes? Does rabbitMQ will able to buffer the messages until consumer repared? Or all the messages will be processed with error (so badly processed) and thus purged from the queue? Sorry for a stupid question probabely..

**Comment by ricbra** [comment]
This depends on how you configure your queue and RabbitMQ.

If the processing fails (e.g. your PHP applications crashes) the rabbitmq-cli-consumer will send a nack to RabbitMQ, so it will try to reprocess your message. It depends on your configuration what happens with the message after that. Default configuration will reprocess the message. 

You should test these kind of things on your development environment before going into production.
