### ISSUE TITLE
How to see consumer error?

### ISSUE THREAD

**Issue by peterpribylina** [ricbra/rabbitmq-cli-consumer#17]
Hello, sometimes the error appears in appropriate error log file (defined in the config file) but sometimes I can see only below line in error log. How to see what happens?

```
2015/07/08 14:55:38 Failed: 
2015/07/08 14:55:38 Error: fork/exec app/console: no such file or directory
```

**Comment by ricbra** [comment]
Based on tiny bit of information I have absolutely no clue what's happening or what problem you're experiencing. Please provide more information so I can reproduce the issue.

**Comment by peterpribylina** [comment]
Well, the command script is working fine, I tested with simulated serialized message.

My cli consumer can work fine but need to stop/restart it (sometimes queue purge needed): 

```
/rabbitmq-cli-consumer -c /rabbitmq/configuration_error_logger.conf -e "app/console project:consumer:error-logger -e=prod" -V
```

But there can be a situation when execution fails, without any explicit error and I'm just receiving constantly this message:

```
tail -f rabbitmq/rabbitmq-cli-consumer/error_log_error.log 
2015/07/08 21:04:24 Failed: 
2015/07/08 21:04:24 Error: fork/exec app/console: no such file or directory
2015/07/08 21:04:24 Failed: 
2015/07/08 21:04:24 Error: fork/exec app/console: no such file or directory
2015/07/08 21:04:24 Failed: 
2015/07/08 21:04:24 Error: fork/exec app/console: no such file or directory
2015/07/08 21:04:24 Failed: 
2015/07/08 21:04:24 Error: fork/exec app/console: no such file or directory
2015/07/08 21:04:24 Failed: 
2015/07/08 21:04:24 Error: fork/exec app/console: no such file or directory
2015/07/08 21:04:24 Failed: 
2015/07/08 21:04:24 Error: fork/exec app/console: no such file or directory
2015/07/08 21:04:24 Failed: 
....
```

My exchange is a direct type. 
Version: rabbitmq-cli-consumer version 1.1.0

**Comment by tilk-theapp** [comment]
In fact, I have a similar problem described in #2

**Comment by ricbra** [comment]
According to the error the path does not exist. You're using a relative path: <code>app/console project:consumer:error-logger -e=prod</code>. What happens if you try full path:

```
/rabbitmq-cli-consumer -c /rabbitmq/configuration_error_logger.conf -e "/home/your-user/app/console project:consumer:error-logger -e=prod" -V
```

**Comment by tilk-theapp** [comment]
If I change the path to app/console to a full location of php folder I receive the same problem:

```
2015/07/09 08:41:29 Error: fork/exec /usr/bin/phpapp/console: no such file or directory
2015/07/09 08:41:29 Processing message...
2015/07/09 08:41:29 Failed. Check error log for details.
```

Another problem is the my logs (error and info) which are flooding the disk capacity as it continuosly producing messages.

**Comment by peterpribylina** [comment]
Yes, seems it was a problem, thank you.

Anyways, I use to receive another kind of error in some cases (but I don't have more precisions):

```
2015/07/09 11:12:49 Error: fork/exec /domain/current/app/console: argument list too long
2015/07/09 11:12:49 Processing message...
2015/07/09 11:12:49 Failed. Check error log for details.
2015/07/09 11:12:49 Failed: 
2015/07/09 11:12:49 Error: fork/exec /var/www/domain/current/app/console: argument list too long
```

Similar to the issue #2. 

When this error occurs I need to stop the script, purge the queue and relaunch.

**Comment by ricbra** [comment]
I think the messages you pass around on the queue are too big. You could try to use the compress functionality. I'm closing this issue as this isn't a (new) bug.

**Comment by peterpribylina** [comment]
If a changed parameter in config file from **Off** to **On** for compression attribute:

```
[rabbitmq]
host = host
username = user
password = pwd
port=port
queue=log_error
compression=On
```

but I receive this kind of error now:

```
2015/07/09 13:59:21 Error: exit status 1
2015/07/09 13:59:21 Compressed message
2015/07/09 13:59:21 Processing message...
2015/07/09 13:59:21 Failed. Check error log for details.
2015/07/09 13:59:21 Failed: 


  [InvalidArgumentException]  
  Invalid input received
```

**Comment by peterpribylina** [comment]
Well, it probably happens when my message is too big, you're right. Still compression doesn't seem to work.
