### ISSUE TITLE
User Configurable Queue Durability Setting

### ISSUE THREAD

**Issue by hellracer** [ricbra/rabbitmq-cli-consumer#20]
Hi Ric,

I don't know if this has much use, the durability on queue setting is hard coded to true on consumer.go source I tweak config.go and consumer.go to make this user configurable just like what you did on the exchange section, this small change doesn't warrant a pull request afaic, thanks for your client.

--- consumer.go 2015-10-04 06:53:14.955238229 +0800
+++ consumer-mod.go 2015-10-04 06:52:30.962229359 +0800
@@ -101,7 +101,7 @@
    infLogger.Println("Succeeded setting QoS.")

```
infLogger.Printf("Declaring queue \"%s\"...", cfg.RabbitMq.Queue)
```
-   _, err = ch.QueueDeclare(cfg.RabbitMq.Queue, true, false, false, false, nil)
-   _, err = ch.QueueDeclare(cfg.RabbitMq.Queue, cfg.RabbitMq.Durable, false, false, false, nil)
  
  if nil != err {
      return nil, errors.New(fmt.Sprintf("Failed to declare queue: %s", err.Error()))

--- config.go   2015-10-04 06:55:54.460239866 +0800
+++ config-mod.go   2015-10-04 06:55:42.065235967 +0800
@@ -13,6 +13,7 @@
        Port        string
        Vhost       string
        Queue       string
-       Durable     bool
      Compression bool
  }
  Prefetch struct {

**Comment by ricbra** [comment]
Hi @hellracer 

Thanks. I will add this in the v2 version which is currently in development. Current version will only receive bugfixes.

**Comment by ricbra** [comment]
This is configurable in the v2 branch, closing this one.
