### ISSUE TITLE
Producer/Consumer same VM on 4G ram

### ISSUE THREAD

**Issue by hellracer** [ricbra/rabbitmq-cli-consumer#21]
Hi Ric,

I know this is not the right forum to ask this, but i'm going to ask anyway. I spawn 3 consumers I notice that I can only consume 46 message and acknowledge the message at peak. the PHP code that your client is calling is virtually doing nothing, I just confirm the message exit(0); and nothing else in there.

prefetch count was set to 3,5,10,20 and nothing seems to work for me :) I can stress the queue at ease but consuming is really slow.

Thanks in advance

**Comment by ricbra** [comment]
Do you have some stats of other consumers (pure PHP consumers maybe?) to compare with? We don't have that high loads on our consumers so I don't recognise the problem (but I don't deny it exists).

**Comment by hellracer** [comment]
HI Richard,

Thanks for the reply, I can easily reproduce it at will send the stats in a short while.

Best

---

On Mon, 10/5/15, Richard van den Brand notifications@github.com wrote:

 Subject: Re: [rabbitmq-cli-consumer] Producer/Consumer same VM on 4G ram (#21)
 To: "ricbra/rabbitmq-cli-consumer" rabbitmq-cli-consumer@noreply.github.com
 Cc: "hellracer" loloski@yahoo.com
 Date: Monday, October 5, 2015, 2:58 PM

 Do you have some stats of other
 consumers (pure PHP consumers maybe?) to compare with? We
 don't have that high loads on our consumers so I
 don't recognise the problem (but I don't deny it
 exists).

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by ricbra** [comment]
Cool, thanks!

**Comment by hellracer** [comment]
Hi Ric,

Please see below stats as requested, please see below PHP code as well.

![stats](https://cloud.githubusercontent.com/assets/3840828/10300189/588c42be-6c26-11e5-9221-ea69cccee370.png)

basically the php code is just like this

#!/usr/bin/env php56
<?php
$message = $argv[1];
$original = base64_decode($message);
exit(0);
?>

**Comment by ricbra** [comment]
And do you also have stats on the same VM with pure PHP consumer? So without my client?
