### ISSUE TITLE
Inconsistent versions

### ISSUE THREAD

**Issue by matatirosolutions** [ricbra/rabbitmq-cli-consumer#30]
First off, a huge THANKS for this library, and your blog post which lead to this project - It's saved me a ton of time, and discovering all the pitfalls you did myself...!

Now my issue... I installed the version from github on my development (OS X) machine and it says it's version 1.1.0.

I then installed the version on a project staging server (Ubuntu 14.10) using the APT instructions. It also says it's version 1.1.0, however the -i flag seems to be missing from the APT version.

Any chance that you could increment both the version numbers, and the version in the APT repo so that we get the -i goodness through apt-get...?

**Comment by ricbra** [comment]
There have been some updates last week, I'll try to update the APT package a.s.a.p. It's on my todo list.

**Comment by ricbra** [comment]
I've releases 1.2.0 both on Github and the APT repository. Thank you for your patience :).
