### ISSUE TITLE
Invalid imports on 2.0

### ISSUE THREAD

**Issue by miguelsimoes** [ricbra/rabbitmq-cli-consumer#40]
On file main.go and config/config.go, the gcfg package needs to be updated to match the correct address, since code.google.com is no longer available.

config/config.go:10:2: cannot find package "code.google.com/p/gcfg" in any of:
    /usr/lib/go-1.6/src/code.google.com/p/gcfg (from $GOROOT)
    <some_path>/src/code.google.com/p/gcfg (from $GOPATH)
main.go:12:2: cannot find package "gopkg.in/p/gcfg" in any of:
    /usr/lib/go-1.6/src/gopkg.in/p/gcfg (from $GOROOT)
    <some-path>/src/gopkg.in/p/gcfg (from $GOPATH)

To get it to work I needed to update both files from "code.google.com/p/gcfg" to gopkg.in/gcfg.v1 after that the build command worked as expected and the binary was generated.

**Comment by ricbra** [comment]
Hi @miguelsimoes 

Could you open a PR to fix this? Thanks in advance.

**Comment by ricbra** [comment]
Fixed now.
