### ISSUE TITLE
Option to pass additional parameters to consumer e.g. queue name

### ISSUE THREAD

**Issue by andrefigueira** [ricbra/rabbitmq-cli-consumer#45]
Hello!

I'm using this for a project that will have many different kinds of workers, and these workers may be used by different clients, so the worker will be the same, but the queue will be different.

I've tried thinking of multiple ways of dealing with the configuration, as I wouldn't want to have 1 config.ini per client/worker as my `rabbitmq-cli-consumer` will be connecting to the same instance of rabbit so I can see a scenario where I end up with tens of different `config.ini` per `rabbitmq-cli-consumer`, where the only difference would be the queue that' it's listening to.

With that In mind, I've thought, what If the consumer could accept additional arguments, for example:

```
rabbitmq-cli-consumer -e "/my/console my-command" -c /path/to/rabbit.ini -q client-specific-queue-name
```

Does this sound like something that would be considered if I were to make the amendments and submit a pull request?

**Comment by andrefigueira** [comment]
I'll be happy to do myself and submit a PR, purpose of ticket is to know, If I go ahead and do, if it's a feature you'd be happy to accept

**Comment by ricbra** [comment]
This sounds like a good idea. Looking forward to your PR 👍

**Comment by ricbra** [comment]
Closing this for now.
