### ISSUE TITLE
Per env variables

### ISSUE THREAD

**Issue by miquel-angel** [ricbra/rabbitmq-cli-consumer#60]
Hi,

it would be really nice if we could also configure the daemon via flags and/or environment vars, not only by using the config file. We are using docker containers and it's easier to run the daemon this way :-)

For example:
```
rabbitmq-cli-consumer -h [host] -u [username] -p [password] -P [PORT] -v [vhost] -q [queue]
```

**Comment by vgoodvin** [comment]
See the "2.0" branch

**Comment by miquel-angel** [comment]
Ah oks, Thanks!

Sorry
