### ISSUE TITLE
Make logging optionnal

### ISSUE THREAD

**Issue by chaouchAbderraouf** [ricbra/rabbitmq-cli-consumer#64]
Hi,

I'm using this project for RabbitMQ consumers, but i have my own logging logic and i don't need to have logs (specially for info level). 
So is there a way to make logging optionnal/configurable per level?
Example 1 : **Inside the configuration** 
```
[logs]
error = true
info = false
```
OR 
```
[logs]
error = false
info = false
```

Example 2: **By overriding attributes from the command**
`rabbitmq-cli-consumer -e "/path/to/your/app argument --flag" -c /path/to/your/configuration.conf --log-level=error`

`rabbitmq-cli-consumer -e "/path/to/your/app argument --flag" -c /path/to/your/configuration.conf --log-level=info`

**Comment by ricbra** [comment]
Hi @chaouchAbderraouf 

This project has been discontinued. Checkout the official fork where the work has continued: https://github.com/corvus-ch/rabbitmq-cli-consumer

**Comment by chaouchAbderraouf** [comment]
Hi @ricbra .
Thank you for repling , it seems that this optionnal logging is supported in this project. :+1:
