### ISSUE TITLE
Routing and RabbitMQBundle consumer usage

### ISSUE THREAD

**Issue by matteosister** [ricbra/rabbitmq-cli-consumer#8]
Hi! Thanks for this library!
We have a large application built with symfony2 and a pretty big amount of messaging involved. Right now we have more then 20 queues. We exclusively use topic routing.
We are dealing with the problems [you are discussing here](http://blog.vandenbrand.org/2015/01/09/symfony2-and-rabbitmq-lessons-learned/) about long running php commands.

I have two questions:
- **how about assigning the consumer to the correct queue/routing key?**

RabbitMQBundle does the magic of defining a yaml configuration file where, for every consumer, you put all the rabbit stuff like:
- the queue name
- the routing keys it listen to
- the callback, which is the service that gets called and stays is up in endless mode. 

How do you bypass that with this library?
- **how much effort do you think is needed to adapt this library to call the callback service instead of a custom command?**

I'm thinking about a simple command that takes the callback name (maybe from RabbitMQBundle configuration file...) and directly calls the **execute** function with the encoded message.

Obviously we could transform everything to a command, but it would be a big work, and we eventually lose the yaml configuration file that keeps everything togheter.

Any ideas?

**Comment by ricbra** [comment]
Hi @matteosister ,

Nice to hear you're interested in my library!

Regarding your questions:
- Currently there isn't any support to configure the routing key used to bind the queue (its hardcoded to an empty string "", see https://github.com/ricbra/rabbitmq-cli-consumer/blob/master/consumer/consumer.go#L126). This shouldn't be very hard to add.
- The callback service you talk about is the same problem as in https://github.com/ricbra/rabbitmq-cli-consumer/issues/3? Could you confirm that?

Next few weeks I'm busy with some not OSS projects, so will be a few weeks before I have some time to spent on the Go consumer unfortunately :disappointed:

**Comment by satboy78** [comment]
Hi  @matteosister ,
I'm Matteo, I work for Mtv Viacom Emea in Milan, and here we are using RabbitMQBundle as well; as mentioned by Richard, I opened an issue #3 

If you want we can meet at [PugMi](http://milano.grusp.org/2015/04/incontro-di-aprile-giovedi-9-ore-1930/) to talk about this, share thoughts about long running php commands and possible solutions.

Bye

**Comment by matteosister** [comment]
Hi @satboy78! Sadly tonight I cannot be there....but my coworker @aleinside will! So speak to him, maybe something will pop up. (maybe some collaboration on this project?)

Really sorry about this! Hope to meet you next month!

**Comment by satboy78** [comment]
Hi @matteosister, 
maybe next week we could talk on skype and find a way to cooperate on this project.
my skypeId is satboy78

**Comment by ricbra** [comment]
If you guys gonna work on some improvements on this project: could you let me know? Perhaps a WIP PR so I can see what's happing would be nice :+1: .

**Comment by satboy78** [comment]
sure, Richard!

**Comment by mbiagetti** [comment]
:+1:

**Comment by Gingonic** [comment]
I guys any word on this? Would be quite interesting for us too

**Comment by ricbra** [comment]
I've recently picked up working on v2 again. No ETA unfortunately. See #13 for current progress.

**Comment by laudeco** [comment]
Hello @ricbra ,
the feature of routing key is very useful for us too but I don't see it in #13 , could you confirm that this feature will be developed in it ?

Regards
Laurent

**Comment by ricbra** [comment]
Hi @laudeco 

This is certainly something that I'll try to implement. The v2 should have no missing features. Keep an eye on this repo. I think release will be somewhere in Q4 2015.

**Comment by ricbra** [comment]
I've implemented configurable routing-key support in the v2 branch. Also RPC support is added in that branch.

Directly calling the callback as you requested is not possible, because the client somehow has to call some php file to get access to the service. 

If you want you are welcome to try the v2 branch. You need to compile it yourself, but that shouldn't be too hard with Go.
