### ISSUE TITLE
Add command line argument option in config file, and add init script

### ISSUE THREAD

**Issue by jskarpe** [ricbra/rabbitmq-cli-consumer#9]
I would like to use rabbitmq-cli-consumer as a service.

Example:

service rabbitmq-cli-consumer start
<read /etc/rabbitmq-cli-consumer.conf>
Execute scripts: "/home/vagrant/current/app/console wb:consumer:mail --env=prod" when receiving queue item (as defined in config).

Ideally, it should work with Upstart as well as Systemd.

**Comment by ricbra** [comment]
Did you consider [Supervisor](http://supervisord.org/) which is well suited for this problem?

Imho there are a couple of problems with bundling this library with a startup script:
- you have to maintain a version for both Debian and RHEL 
- you have to maintain a version for Upstart and Systemd
- most users have multiple instances of rabbitmq-cli-consumer running so one script/service is insufficient

All these problems are solved when using Supervisor to take care of the daemonizing. I have multiple consumers per project, and one server has often more then one project. 

I'm +1 on adding some info to the docs on how to configure this, but I'm -1 on adding a startup script to the library.

**Comment by jskarpe** [comment]
Supervisor adds another layer of complexity I'm trying to avoid. I suggest that rabbitmq-cli-consumer have separate configuration sections for separate queues, and spawn separate processes for separate queues. Since this is ultimately a service solution, I strongly believe that working as a self contained service is a better approach for scaling down. Having init scripts doesn't exclude the use of Supervisor, it just doesn't enforce it.

**Comment by ricbra** [comment]
I agree the ideal solution is to not depend on external tools. Personally I like the php-fpm configuration where you can add as much pools as you want. Implementing such a strategy - including all the cool stuff like a reload on USR2 signal, validate config before reload|restart etc.) - would take a serious amount of time. These kind of features would be nice for a v2 but given the amount of spare time I currenty have not something that will be implemented very soon unfortunately.

Instead I would like to focus on implementing the some missing core features first (like RPC for example), and perhaps later add stuff like service registration and multiple processes. 

That being said and given the fact that the default init script and config as proposed only work for one queue I would propose to add this in a later version in a more mature form. Power users shouldn't have any problem with creating an init script and service definition by them self (given that most of them use configuration tools like Puppet, Ansible etc.).
